# Generated by Django 4.0.5 on 2022-09-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
                ('numero', models.IntegerField()),
                ('logradouro', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=15)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIDoceFestas.bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('idade', models.IntegerField()),
                ('entrega', models.DateField()),
                ('recebimento', models.DateField()),
                ('data_festa', models.DateField()),
                ('especificacoes', models.CharField(max_length=500)),
                ('aniversariante', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIDoceFestas.cliente')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIDoceFestas.tema')),
            ],
        ),
    ]
